include(../../cmake/SanitizerFlags.cmake)

# Add subdirectories for all modules
add_subdirectory(wave)
add_subdirectory(saver)
add_subdirectory(layers)
add_subdirectory(tensor)
add_subdirectory(wavelet)
add_subdirectory(utility)
add_subdirectory(statistics)
add_subdirectory(optimizers)
add_subdirectory(dataLoaders)
add_subdirectory(initializers)
add_subdirectory(linearAlgebra)
add_subdirectory(paraconsistent)