#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SOURCE_DIR="${PROJECT_ROOT}/.wiki"
OUTPUT_DIR="${PROJECT_ROOT}/out/anytype/wiki"
INCLUDE_GRAPHIFY_OUT=0
CLEAN_OUTPUT=0
DRY_RUN=0

print_usage() {
    cat <<'USAGE'
Usage: scripts/export_wiki_for_anytype.sh [options]

Prepare a Markdown folder that can be imported into Anytype.

Options:
  --source <dir>            Source wiki directory (default: .wiki)
  --output <dir>            Export directory (default: out/anytype/wiki)
  --include-graphify-out    Include .wiki/graphify-out content
  --clean                   Remove output directory before export
  --dry-run                 Show what would be copied without writing files
  -h, --help                Show this help message
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --source)
            SOURCE_DIR="$2"
            shift 2
            ;;
        --output)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --include-graphify-out)
            INCLUDE_GRAPHIFY_OUT=1
            shift
            ;;
        --clean)
            CLEAN_OUTPUT=1
            shift
            ;;
        --dry-run)
            DRY_RUN=1
            shift
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            print_usage
            exit 2
            ;;
    esac
done

if [[ ! -d "${SOURCE_DIR}" ]]; then
    echo "Source directory not found: ${SOURCE_DIR}" >&2
    exit 1
fi

if [[ ${CLEAN_OUTPUT} -eq 1 && -d "${OUTPUT_DIR}" ]]; then
    rm -rf "${OUTPUT_DIR}"
fi

mkdir -p "${OUTPUT_DIR}"

RSYNC_ARGS=(
    -a
    --prune-empty-dirs
)

if [[ ${INCLUDE_GRAPHIFY_OUT} -ne 1 ]]; then
    RSYNC_ARGS+=(--exclude='graphify-out/***')
fi

RSYNC_ARGS+=(
    --include='*/'
    --include='*.md'
    --include='*.png'
    --include='*.jpg'
    --include='*.jpeg'
    --include='*.gif'
    --include='*.webp'
    --include='*.svg'
    --include='*.pdf'
    --exclude='*'
)

if [[ ${DRY_RUN} -eq 1 ]]; then
    RSYNC_ARGS+=(--dry-run --itemize-changes)
fi

rsync "${RSYNC_ARGS[@]}" "${SOURCE_DIR}/" "${OUTPUT_DIR}/"

if [[ ${DRY_RUN} -eq 1 ]]; then
    echo "Dry run complete."
    exit 0
fi

export SOURCE_DIR OUTPUT_DIR

# Normalize wiki-style links so Anytype imports them as standard Markdown links.
python3 - "${OUTPUT_DIR}" <<'PY'
import pathlib
import re
import sys

output_dir = pathlib.Path(sys.argv[1])

pat_label = re.compile(r"\[\[([^\]|]+)\|([^\]]+)\]\]")
pat_plain = re.compile(r"\[\[([^\]]+)\]\]")

def normalize_target(target: str) -> str:
    target = target.strip()
    if "/" not in target and not target.endswith(".md") and not re.search(r"\.[A-Za-z0-9]+$", target):
        target = f"{target}.md"
    return target

for md_file in output_dir.rglob("*.md"):
    original = md_file.read_text(encoding="utf-8")

    def repl_label(match: re.Match[str]) -> str:
        target = normalize_target(match.group(1))
        label = match.group(2).strip()
        return f"[{label}]({target})"

    def repl_plain(match: re.Match[str]) -> str:
        label = match.group(1).strip()
        target = normalize_target(label)
        return f"[{label}]({target})"

    updated = pat_label.sub(repl_label, original)
    updated = pat_plain.sub(repl_plain, updated)

    if updated != original:
        md_file.write_text(updated, encoding="utf-8")
PY

cat > "${OUTPUT_DIR}/ANYTYPE_IMPORT.md" <<EOF
# Anytype Import Folder

Generated by: scripts/export_wiki_for_anytype.sh
Source: ${SOURCE_DIR}
Generated at (UTC): $(date -u +"%Y-%m-%dT%H:%M:%SZ")

Import this folder in Anytype using:
Library -> Import -> Markdown & CSV
EOF

echo "Export complete: ${OUTPUT_DIR}"
echo "Next step: In Anytype, import this folder as Markdown."
