add_executable(
    initializers_gtest 
        initializers_gtest.cpp
)
target_link_libraries(initializers_gtest 
    PRIVATE 
        google_test 
        Eigen3::Eigen 
        initializers
        tensor
)

target_include_directories(initializers_gtest 
    PRIVATE 
        ${EIGEN3_INCLUDE_DIR}
)
include(GoogleTest)
gtest_discover_tests(initializers_gtest)
configure_eigen_parallel_target(initializers_gtest)