/**
 * @file pytorch_parity_gtest.cpp
 * @brief Ground-truth parity tests: compare this library against PyTorch.
 *
 * References are generated by scripts/testing/gen_pytorch_refs.py (requires
 * torch) into fixtures/pytorch_refs.npz — committed so this test needs no torch
 * at build/CI time. Each case sets the same weights + input into our layer, runs
 * forward/backward, and asserts EXPECT_NEAR against PyTorch's output/gradients.
 *
 * Regenerate after touching a covered layer:
 *   software/nn/.venv/bin/python software/nn/scripts/testing/gen_pytorch_refs.py
 */
#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <string>

#include "cnpy.h"

#include "layers/Layers.hpp"
#include "layers/convolution/Conv1d.hpp"
#include "layers/convolution/Conv2d.hpp"
#include "layers/convolution/MaxPool1d.hpp"
#include "layers/convolution/MaxPool2d.hpp"
#include "layers/lstm/LSTMLayer.hpp"
#include "layers/spiking/LifBPTT.hpp"
#include "tensor/Tensor.hpp"

namespace
{
constexpr float kTol = 1e-4F;

const cnpy::npz_t& refs()
{
    static const cnpy::npz_t data = [] {
        const std::filesystem::path p =
            std::filesystem::path(__FILE__).parent_path() / "fixtures" / "pytorch_refs.npz";
        return cnpy::npz_load(p.string());
    }();
    return data;
}

const cnpy::NpyArray& arr(const std::string& key)
{
    const auto it = refs().find(key);
    EXPECT_NE(it, refs().end()) << "missing fixture key: " << key;
    return it->second;
}

// Build a 2-D tensor from a fixture array (row-major, C order).
nn::Tensor make2d(const cnpy::NpyArray& a)
{
    nn::Tensor t(static_cast<nn::Index>(a.shape[0]), static_cast<nn::Index>(a.shape[1]));
    const float* d = a.data<float>();
    for (nn::Index k = 0; k < t.size(); ++k) t.at(k) = d[static_cast<size_t>(k)];
    return t;
}

// Build a 3-D (B,T,D) tensor from a fixture array.
nn::Tensor make3d(const cnpy::NpyArray& a)
{
    nn::Tensor t(std::vector<nn::Index>{static_cast<nn::Index>(a.shape[0]),
        static_cast<nn::Index>(a.shape[1]), static_cast<nn::Index>(a.shape[2])});
    const float* d = a.data<float>();
    for (nn::Index k = 0; k < t.size(); ++k) t.at(k) = d[static_cast<size_t>(k)];
    return t;
}

// Build a tensor of the fixture array's own shape (any rank), row-major.
nn::Tensor make_nd(const cnpy::NpyArray& a)
{
    std::vector<nn::Index> shape;
    shape.reserve(a.shape.size());
    for (size_t s : a.shape) shape.push_back(static_cast<nn::Index>(s));
    nn::Tensor t(shape);
    const float* d = a.data<float>();
    for (nn::Index k = 0; k < t.size(); ++k) t.at(k) = d[static_cast<size_t>(k)];
    return t;
}

// Overwrite an existing tensor's values from a fixture array (same element count).
void fill_from(nn::Tensor& dst, const cnpy::NpyArray& a)
{
    ASSERT_EQ(static_cast<size_t>(dst.size()), a.num_vals);
    const float* d = a.data<float>();
    for (nn::Index k = 0; k < dst.size(); ++k) dst.at(k) = d[static_cast<size_t>(k)];
}

void expect_close(const nn::Tensor& got, const cnpy::NpyArray& ref, const std::string& what)
{
    ASSERT_EQ(static_cast<size_t>(got.size()), ref.num_vals) << what << ": size mismatch";
    const float* d = ref.data<float>();
    for (nn::Index k = 0; k < got.size(); ++k)
        EXPECT_NEAR(got.at(k), d[static_cast<size_t>(k)], kTol) << what << " at flat index " << k;
}
} // namespace

// ── Linear: forward + input/weight/bias gradients ─────────────────────────────
TEST(PyTorchParity, Linear)
{
    const int n = static_cast<int>(arr("linear_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "linear_" + std::to_string(i) + "_";
        const auto& W = arr(p + "weight");
        const int out_f = static_cast<int>(W.shape[0]);
        const int in_f = static_cast<int>(W.shape[1]);

        nn::Linear lin(in_f, out_f);
        fill_from(lin.weight, W);
        fill_from(lin.bias, arr(p + "bias"));

        nn::Tensor x = make2d(arr(p + "input"));
        nn::Tensor y = lin.forward(x, true);
        expect_close(y, arr(p + "output"), p + "output");

        nn::Tensor go = make2d(arr(p + "grad_output"));
        nn::Tensor gi = lin.backward(go);
        expect_close(gi, arr(p + "grad_input"), p + "grad_input");
        expect_close(lin.weight.grad(), arr(p + "grad_weight"), p + "grad_weight");
        expect_close(lin.bias.grad(), arr(p + "grad_bias"), p + "grad_bias");
    }
}

// ── Elementwise activations: forward + backward ───────────────────────────────
template <typename Layer>
void check_activation(const std::string& name)
{
    const std::string p = "act_" + name + "_";
    Layer layer;
    nn::Tensor x = make2d(arr(p + "input"));
    nn::Tensor y = layer.forward(x, true);
    expect_close(y, arr(p + "output"), p + "output");

    nn::Tensor go = make2d(arr(p + "grad_output"));
    nn::Tensor gi = layer.backward(go);
    expect_close(gi, arr(p + "grad_input"), p + "grad_input");
}

TEST(PyTorchParity, Tanh) { check_activation<nn::Tanh>("tanh"); }
TEST(PyTorchParity, Sigmoid) { check_activation<nn::Sigmoid>("sigmoid"); }
TEST(PyTorchParity, ReLU) { check_activation<nn::ReLU>("relu"); }
TEST(PyTorchParity, LeakyReLU) { check_activation<nn::LeakyReLU>("leaky"); }

// ── MSELoss: scalar loss + gradient w.r.t. prediction ─────────────────────────
TEST(PyTorchParity, MSELoss)
{
    nn::MSELoss loss;
    loss.set_target(make2d(arr("mse_target")));
    nn::Tensor pred = make2d(arr("mse_pred"));
    nn::Tensor l = loss.forward(pred, true);
    EXPECT_NEAR(l.at(0, 0), arr("mse_loss").data<float>()[0], kTol);

    nn::Tensor gp = loss.backward(pred);
    expect_close(gp, arr("mse_grad_pred"), "mse_grad_pred");
}

// ── LSTMLayer: forward (all hidden states) for a batched sequence ──────────────
//
// Our LSTM uses rational-approximation sigmoid/tanh (FastActivations.hpp) for
// speed, so it cannot bit-match PyTorch's exact activations. Two checks:
//   1. Tight vs. a numpy reference using the *same* rational approximation —
//      proves the recurrence, gate order (i,f,o,g), and weight orientation are
//      correct.
//   2. Loose vs. PyTorch's exact-activation output — documents the accuracy gap
//      the fast activations introduce (bounded well under the saturation error).
TEST(PyTorchParity, LSTMLayerForward)
{
    constexpr float kApproxBound = 0.25F; // max deviation vs. exact-activation LSTM
    const int n = static_cast<int>(arr("lstm_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "lstm_" + std::to_string(i) + "_";
        const auto dims = arr(p + "dims").data<int64_t>();
        const int D = static_cast<int>(dims[2]);
        const int H = static_cast<int>(dims[3]);

        nn::LSTMLayer layer(D, H);
        // Fixture weights are already in our gate order (i,f,o,g) with merged bias.
        fill_from(layer.W_, arr(p + "W"));
        fill_from(layer.U_, arr(p + "U"));
        fill_from(layer.b_, arr(p + "b"));

        nn::Tensor x = make3d(arr(p + "input"));
        layer.reset_state();
        nn::Tensor y = layer.forward(x, false);

        // (1) Exact match against the same rational-approx recurrence.
        expect_close(y, arr(p + "output_approx"), p + "output_approx");

        // (2) Bounded deviation from PyTorch's exact LSTM.
        const auto& torch_out = arr(p + "output");
        ASSERT_EQ(static_cast<size_t>(y.size()), torch_out.num_vals);
        const float* d = torch_out.data<float>();
        float max_abs = 0.0F;
        for (nn::Index k = 0; k < y.size(); ++k)
            max_abs = std::max(max_abs, std::abs(y.at(k) - d[static_cast<size_t>(k)]));
        EXPECT_LT(max_abs, kApproxBound)
            << p << "max deviation vs. exact PyTorch LSTM = " << max_abs;
    }
}

// ── LifBPTT spiking neuron vs snnTorch Leaky ──────────────────────────────────
// Our recurrence v[t]=beta*v[t-1]+input[t], spike on v>V_th, subtract/zero reset
// matches snn.Leaky(beta, threshold, reset_mechanism). R=C=1, time_step=-ln(beta)
// so beta = exp(-time_step/(R*C)) reproduces snnTorch's beta.
TEST(PyTorchParity, LifBPTTvsSnnTorch)
{
    const int n = static_cast<int>(arr("lif_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "lif_" + std::to_string(i) + "_";
        const auto dims = arr(p + "dims").data<int64_t>();
        const int T = static_cast<int>(dims[0]);
        const int B = static_cast<int>(dims[1]);
        const int F = static_cast<int>(dims[2]);
        const float* prm = arr(p + "params").data<float>();
        const float time_step = prm[0];
        const float R = prm[1];
        const float C = prm[2];
        const float vth = prm[3];
        const bool reset_zero = prm[4] > 0.5F;
        const bool readout = prm[5] > 0.5F;

        nn::LifBPTT lif(T, time_step, R, C, vth, reset_zero, 0.0F, readout);

        // Fixture input is (T,B,F) C-order == time-major (T*B, F) rows (t0 batch,
        // then t1 batch, …) — exactly what LifBPTT expects.
        const auto& in = arr(p + "input");
        nn::Tensor x(static_cast<nn::Index>(T * B), static_cast<nn::Index>(F));
        const float* d = in.data<float>();
        for (nn::Index k = 0; k < x.size(); ++k) x.at(k) = d[static_cast<size_t>(k)];

        lif.reset_state();
        nn::Tensor y = lif.forward(x, false);

        // readout → membrane (compare to snnTorch mem); spike mode → spike train.
        expect_close(y, arr(p + (readout ? "mem" : "spk")), p + (readout ? "mem" : "spk"));
    }
}

// ── LifBPTT readout backward vs snnTorch autograd (exact BPTT temporal grad) ──
// Pure leaky integrator (readout mode, no spike/reset): dL/dinput through
// v[t]=beta*v[t-1]+input[t] for loss = sum(all membranes) must match snnTorch's
// autograd exactly (no surrogate/reset involved).
TEST(PyTorchParity, LifBPTTReadoutBackward)
{
    const int n = static_cast<int>(arr("lifbw_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "lifbw_" + std::to_string(i) + "_";
        const auto dims = arr(p + "dims").data<int64_t>();
        const int T = static_cast<int>(dims[0]);
        const int B = static_cast<int>(dims[1]);
        const int F = static_cast<int>(dims[2]);
        const float* prm = arr(p + "params").data<float>();

        nn::LifBPTT lif(T, prm[0], prm[1], prm[2], /*V_th=*/1.0F,
            /*reset_zero=*/false, /*reset_potential=*/0.0F, /*readout_mode=*/true);

        // Arbitrary input; only the gradient path is checked. Use a fixed pattern.
        nn::Tensor x(static_cast<nn::Index>(T * B), static_cast<nn::Index>(F));
        for (nn::Index k = 0; k < x.size(); ++k)
            x.at(k) = 0.1F * static_cast<float>((k % 7) - 3);

        lif.reset_state();
        (void) lif.forward(x, true);
        // loss = sum(all membranes) → dL/d(membrane)=1 everywhere.
        nn::Tensor grad_out(static_cast<nn::Index>(T * B), static_cast<nn::Index>(F));
        for (nn::Index k = 0; k < grad_out.size(); ++k) grad_out.at(k) = 1.0F;

        nn::Tensor grad_in = lif.backward(grad_out);
        expect_close(grad_in, arr(p + "grad_input"), p + "grad_input");
    }
}

// ── Conv1d vs torch.nn.Conv1d (valid, stride 1) ───────────────────────────────
TEST(PyTorchParity, Conv1d)
{
    const int n = static_cast<int>(arr("conv1d_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "conv1d_" + std::to_string(i) + "_";
        const auto dims = arr(p + "dims").data<int64_t>();
        const int Cin = static_cast<int>(dims[1]);
        const int Cout = static_cast<int>(dims[2]);
        const int K = static_cast<int>(dims[4]);

        nn::Conv1d conv(Cin, Cout, K, /*stride=*/1, /*padding=*/0, /*dilation=*/1);
        conv.set_weights(make2d(arr(p + "weight"))); // (Cin*K, Cout)
        conv.set_bias(make2d(arr(p + "bias")));      // (1, Cout)

        nn::Tensor x = make_nd(arr(p + "input"));    // (N, Cin, L)
        nn::Tensor y = conv.forward(x, false);       // (N, Cout, L-K+1)
        expect_close(y, arr(p + "output"), p + "output");
    }
}

// ── Conv2d vs torch.nn.Conv2d (valid, stride 1, square kernel) ────────────────
TEST(PyTorchParity, Conv2d)
{
    const int n = static_cast<int>(arr("conv2d_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "conv2d_" + std::to_string(i) + "_";
        const auto dims = arr(p + "dims").data<int64_t>();
        const int Cin = static_cast<int>(dims[1]);
        const int Cout = static_cast<int>(dims[2]);
        const int K = static_cast<int>(dims[5]);

        nn::Conv2d conv(Cin, Cout, K, /*stride=*/1, /*padding=*/0, /*dilation=*/1);
        conv.set_weights(make2d(arr(p + "weight"))); // (Cin*K*K, Cout)
        conv.set_bias(make2d(arr(p + "bias")));      // (1, Cout)

        nn::Tensor x = make_nd(arr(p + "input"));    // (N, Cin, H, W)
        nn::Tensor y = conv.forward(x, false);       // (N, Cout, H-K+1, W-K+1)
        expect_close(y, arr(p + "output"), p + "output");
    }
}

// ── CrossEntropyLoss (softmax+CE, mean) vs torch ──────────────────────────────
TEST(PyTorchParity, CrossEntropyLoss)
{
    const int n = static_cast<int>(arr("ce_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "ce_" + std::to_string(i) + "_";
        nn::CrossEntropyLoss loss;
        loss.set_target(make2d(arr(p + "target"))); // one-hot (N,C)
        nn::Tensor logits = make2d(arr(p + "logits"));
        nn::Tensor l = loss.forward(logits, true);
        EXPECT_NEAR(l.at(0, 0), arr(p + "loss").data<float>()[0], kTol) << p << "loss";
        nn::Tensor g = loss.backward(logits);
        expect_close(g, arr(p + "grad_logits"), p + "grad_logits");
    }
}

// ── MaxPool1d / MaxPool2d (forward) vs torch ──────────────────────────────────
TEST(PyTorchParity, MaxPool1d)
{
    const int n = static_cast<int>(arr("maxpool1d_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "maxpool1d_" + std::to_string(i) + "_";
        const auto pr = arr(p + "params").data<int64_t>();
        nn::MaxPool1d pool(static_cast<int>(pr[0]), static_cast<int>(pr[1]));
        nn::Tensor x = make_nd(arr(p + "input"));   // (N, C, L)
        nn::Tensor y = pool.forward(x, false);
        expect_close(y, arr(p + "output"), p + "output");
    }
}

TEST(PyTorchParity, MaxPool2d)
{
    const int n = static_cast<int>(arr("maxpool2d_num").data<int64_t>()[0]);
    for (int i = 0; i < n; ++i)
    {
        const std::string p = "maxpool2d_" + std::to_string(i) + "_";
        const auto pr = arr(p + "params").data<int64_t>();
        nn::MaxPool2d pool(static_cast<int>(pr[0]), static_cast<int>(pr[1]));
        nn::Tensor x = make_nd(arr(p + "input"));   // (N, C, H, W)
        nn::Tensor y = pool.forward(x, false);
        expect_close(y, arr(p + "output"), p + "output");
    }
}
