/**
 * @file pywt_parity_gtest.cpp
 * @brief Ground-truth parity: C++ wavelet ops vs PyWavelets (pywt).
 *
 * Fixtures (fixtures/pywt_refs.npz, committed) are generated by
 * scripts/testing/gen_pywt_refs.py with mode='periodization' (matching this
 * implementation's circular indexing) and frequency-ordered packet leaves
 * (matching malat()'s high-pass branch swap).
 *
 * Comparison target: per-subband ROOT-ENERGY (L2 norm) via
 * extract_subband_energies() — exactly what the thesis feature pipeline
 * consumes. Band L2 norms are invariant to the circular phase offset between
 * the two implementations while catching wrong filters, tree structure, band
 * ordering, boundary handling, or normalization.
 */
#include <gtest/gtest.h>

#include <cmath>
#include <string>
#include <vector>

#include "cnpy.h"
#include "wavelet/Types.hpp"
#include "wavelet/waveletOperations.hpp"

namespace
{

const std::string kFixture = std::string(TEST_FIXTURE_DIR) + "/pywt_refs.npz";
constexpr int kLevel = 3;
// Filter tables are stored at full double precision (synced from pywt), so
// band norms agree to ~1e-10 relative.
constexpr double kRelTol = 1e-9;

std::vector<double> load_doubles(const std::string& key)
{
    cnpy::npz_t npz = cnpy::npz_load(kFixture);
    auto it = npz.find(key);
    if (it == npz.end()) throw std::runtime_error("fixture key missing: " + key);
    const cnpy::NpyArray& arr = it->second;
    const double* p = arr.data<double>();
    return {p, p + arr.num_vals};
}

void expect_energies_match(
    const std::vector<double>& ours, const std::vector<double>& ref, const std::string& label)
{
    ASSERT_EQ(ours.size(), ref.size()) << label << ": band count differs";
    for (size_t i = 0; i < ref.size(); ++i)
    {
        const double tol = kRelTol * std::max(1.0, std::abs(ref[i]));
        EXPECT_NEAR(ours[i], ref[i], tol) << label << " band " << i;
    }
}

template <typename WaveletTag>
void run_case(const std::string& coeff_name, const std::string& sig_name)
{
    const std::vector<double> signal = load_doubles(sig_name);

    {
        auto res = wavelets::malat(
            signal, wavelets::get_wavelet<WaveletTag>(), wavelets::REGULAR_WAVELET, kLevel);
        auto energies = wavelets::extract_subband_energies(res, kLevel);
        expect_energies_match(energies,
            load_doubles("reg_" + coeff_name + "_L" + std::to_string(kLevel) + "_" + sig_name),
            "regular/" + coeff_name + "/" + sig_name);
    }
    {
        auto res = wavelets::malat(
            signal, wavelets::get_wavelet<WaveletTag>(), wavelets::PACKET_WAVELET, kLevel);
        auto energies = wavelets::extract_subband_energies(res, kLevel);
        expect_energies_match(energies,
            load_doubles("pkt_" + coeff_name + "_L" + std::to_string(kLevel) + "_" + sig_name),
            "packet/" + coeff_name + "/" + sig_name);
    }
}

} // namespace

TEST(PyWtParity, Daub4Sig0)
{
    run_case<wavelets::Daub4>("daub4", "sig0");
}
TEST(PyWtParity, Daub4Sig1)
{
    run_case<wavelets::Daub4>("daub4", "sig1");
}
TEST(PyWtParity, Daub10Sig0)
{
    run_case<wavelets::Daub10>("daub10", "sig0");
}
TEST(PyWtParity, Daub10Sig1)
{
    run_case<wavelets::Daub10>("daub10", "sig1");
}
TEST(PyWtParity, Daub20Sig0)
{
    run_case<wavelets::Daub20>("daub20", "sig0");
}
TEST(PyWtParity, Daub20Sig1)
{
    run_case<wavelets::Daub20>("daub20", "sig1");
}
