find_package(ZLIB REQUIRED)

# Experiment 01 CMake configuration
add_executable(exec_Experiment01
    ${CNPY_SOURCES}
    ${SRC_DIR}/core/initializers/xavier.hpp
    ${SRC_DIR}/core/optimizers/SGDMinimal.hpp
    ${SRC_DIR}/core/optimizers/Adam.hpp
    ${SRC_DIR}/core/optimizers/SGD.hpp
    ${SRC_DIR}/core/layers/Sequential.hpp
    ${SRC_DIR}/core/layers/Linear.hpp
    ${SRC_DIR}/core/layers/ReLU.hpp
    ${SRC_DIR}/core/layers/LeakyReLU.hpp
    ${SRC_DIR}/util/synthetic_spike_data.cpp
    ${SRC_DIR}/util/vectorizationCheck.cpp
    ${SRC_DIR}/util/batching.cpp
    ${SRC_DIR}/core/NnSaver.hpp
    ${SRC_DIR}/core/dataLoaders/AudioLoader.cpp
    ${SRC_DIR}/core/dataLoaders/EEGLoader.cpp
    ${SRC_DIR}/experiments/01/Experiment01.cpp
)

# Include directories
target_include_directories(exec_Experiment01
    PUBLIC
        ${SRC_DIR}
        ${CNPY_DIR}
        ${LIB_DIR}/util
        ${EIGEN3_INCLUDE_DIR}
        ${OpenMP_INCLUDE_DIRS}
        ${CMAKE_SOURCE_DIR}/lib/matio-cpp/include 
		${CMAKE_BINARY_DIR}/lib/matio-cpp/Autogenerated 
		${CMAKE_SOURCE_DIR}/lib/matio/src 
		${CMAKE_BINARY_DIR}/matio/src
)

# Link libraries
target_link_libraries(exec_Experiment01
    PUBLIC
        cnpy
        Eigen3::Eigen
		${ZLIB_LIBRARIES} 
        ${OpenMP_CXX_LIBRARIES}
        matioCpp
)


# Configure Eigen parallelism for the target
configure_eigen_parallel_target(exec_Experiment01)
# End of Experiment 01 CMake configuration