## AutoEncoderTargets.cmake
# Targets for mainProject

add_executable(mainProject
    ${CNPY_SOURCES}
    ${SRC_DIR}/core/initializers/xavier.hpp
    ${SRC_DIR}/core/optimizers/SGDMinimal.hpp
    ${SRC_DIR}/core/optimizers/Adam.hpp
    ${SRC_DIR}/core/optimizers/SGD.hpp
    ${SRC_DIR}/core/layers/Sequential.hpp
    ${SRC_DIR}/core/layers/Linear.hpp
    ${SRC_DIR}/core/layers/Leaky.hpp
    ${SRC_DIR}/core/layers/ReLU.hpp
    ${SRC_DIR}/core/layers/LeakyReLU.hpp
    ${SRC_DIR}/util/vectorizationCheck.cpp
    ${SRC_DIR}/util/batching.cpp
    ${SRC_DIR}/core/NnSaver.hpp
    ${SRC_DIR}/core/dataLoaders/MatFileUtils.cpp
    ${SRC_DIR}/main_app/main.cpp
)

# Link libraries
target_link_libraries(mainProject
    PUBLIC
        cnpy
        Eigen3::Eigen
        ${OpenMP_CXX_LIBRARIES}
        matioCpp
)

# Include directories
target_include_directories(mainProject
    PUBLIC
        ${SRC_DIR}
        ${CNPY_DIR}
        ${LIB_DIR}/util
    ${LIB_DIR}/matio-cpp/include
    ${CMAKE_BINARY_DIR}/lib/matio-cpp/Autogenerated
    ${LIB_DIR}/matio/src
    ${CMAKE_BINARY_DIR}/matio/src
        ${EIGEN3_INCLUDE_DIR}
        ${OpenMP_INCLUDE_DIRS}
)

# Configure Eigen parallelism for the target
configure_eigen_parallel_target(mainProject)