##
## VendorMatioCppShim.cmake
##
## Purpose
## - Fetch and configure `matio-cpp` (C++ wrapper around matio) in a way that is safe
##   for a vendored build: avoid generating install/export artifacts that reference
##   external targets.
##
## Strategy
## - Set `matioCpp_IS_TOP_LEVEL=ON` to reduce upstream packaging side effects.
## - Provide a no-op `install_basic_package_files()` to satisfy upstream calls without
##   emitting export/install metadata.
## - Bridge legacy matio-cpp find logic by seeding `MATIO_INCLUDE_DIR`, `MATIO_LIBRARY`,
##   and `MATIO_FOUND` from the already-configured `matio` target.
##
## Notes
## - This is intentionally a “shim”: it’s about making third-party CMake behave inside
##   this repo. Keep it small and comment-heavy.
##

# VendorMatioCppShim.cmake
# Make matio-cpp configure safely inside the top-level project without
# generating install/export files that would reference external targets.

# Treat matio-cpp as top-level to reduce packaging/export side-effects
set(matioCpp_IS_TOP_LEVEL ON CACHE BOOL "Treat matio-cpp as top-level" FORCE)

# Provide a no-op implementation of install_basic_package_files so the
# vendored matio-cpp project can call it during configure without creating
# export/install files that reference external targets. This avoids editing
# third-party files.
if(NOT COMMAND install_basic_package_files)
  function(install_basic_package_files)
    # intentionally empty to avoid generating install/export files for vendored libs
  endfunction()
endif()

# Include vendored matio-cpp
include(FetchContent)

FetchContent_Declare(
    matio-cpp
    GIT_REPOSITORY https://github.com/ami-iit/matio-cpp.git
    GIT_TAG        v0.3.0 # Pinned to a specific tag for reproducibility
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
)

# The matio-cpp find script is not modern and requires old-style hint variables.
# We set them here based on the 'matio' target created by the previous FetchContent call.
# This is fragile but necessary to bridge the modern and legacy CMake scripts.
if(TARGET matio)
    # Manually construct the path to the library. Based on the build output,
    # matio produces a shared library `libmatio.<ext>` directly in its binary
    # directory (.so on Linux, .dylib on macOS).
    set(MATIO_LIB_PATH "${matio_BINARY_DIR}/libmatio${CMAKE_SHARED_LIBRARY_SUFFIX}")

    set(MATIO_INCLUDE_DIR "${matio_SOURCE_DIR}/src" CACHE INTERNAL "Path to matio headers")
    set(MATIO_LIBRARY "${MATIO_LIB_PATH}" CACHE INTERNAL "Path to matio library")
    set(MATIO_FOUND TRUE CACHE INTERNAL "Indicate that matio is found")
endif()

FetchContent_MakeAvailable(matio-cpp)

# Suppress warnings and clang-tidy
if(TARGET matio-cpp)
    target_compile_options(matio-cpp PRIVATE -w)
    set_target_properties(matio-cpp PROPERTIES CXX_CLANG_TIDY "")
endif()
# In case the target name is matioCpp (some versions/forks might differ)
if(TARGET matioCpp)
    target_compile_options(matioCpp PRIVATE -w)
    set_target_properties(matioCpp PROPERTIES CXX_CLANG_TIDY "")
endif()

target_include_directories(matioCpp SYSTEM
  PUBLIC
    "$<BUILD_INTERFACE:${matio-cpp_SOURCE_DIR}/include>"
    "$<BUILD_INTERFACE:${matio-cpp_BINARY_DIR}/Autogenerated>"
)