#pragma once
// Shim: aliases moved to nn/layers/Layers.hpp (auto-generated by cmake/GenerateLayers.cmake).
// This header is preserved for backward compatibility with existing #include sites.
#include "nn/layers/Layers.hpp"
